[phases.setup]
nixpkgs = ["nodejs", "python310", "postgresql_16", "pip", "gcc"]

[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix client",
  "npm run build --prefix client",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "python manage.py migrate && gunicorn project.wsgi:application --bind 0.0.0.0:8000"
