version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    networks:
      - mynetwork  # Both should be on the same network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mynetwork  # Same network here

networks:
  mynetwork:
    driver: bridge  # Ensure both services are on the same network
