services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    networks:
      - mynetwork  # Ensure the backend is in the same network
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mynetwork  # Ensure nginx is in the same network

networks:
  mynetwork:
    driver: bridge
